import { player } from "./types";
import { team } from "./types";

export const players: player[] = [
  {
    ign: "Levius",
    team: "Bilibili Gaming",
    role: "Sentinel",
    acs: 173,
    kd: 0.92,
    cl: "N/A",
    adr: 114,
    fk: 6,
  },
  {
    ign: "nephh",
    team: "Bilibili Gaming",
    role: "Flex",
    acs: 200,
    kd: 1.04,
    cl: "17.00%",
    adr: 124,
    fk: 7,
  },
  {
    ign: "whzy",
    team: "Bilibili Gaming",
    role: "Duelist",
    acs: 250,
    kd: 1.21,
    cl: "13.00%",
    adr: 154,
    fk: 19,
  },
  {
    ign: "rushia",
    team: "Bilibili Gaming",
    role: "Smokes",
    acs: 196,
    kd: 1.02,
    cl: "10.00%",
    adr: 130,
    fk: 10,
  },
  {
    ign: "Knight",
    team: "Bilibili Gaming",
    role: "Dart",
    acs: 193,
    kd: 1.06,
    cl: "7.00%",
    adr: 128,
    fk: 7,
  },

  {
    ign: "vo0kashu",
    team: "Dragon Ranger Gaming",
    role: "Sentinel",
    acs: 221,
    kd: 1.19,
    cl: "N/A",
    adr: 148,
    fk: 7,
  },
  {
    ign: "SpiritZ1",
    team: "Dragon Ranger Gaming",
    role: "Duelist",
    acs: 211,
    kd: 0.98,
    cl: "N/A",
    adr: 145,
    fk: 18,
  },
  {
    ign: "Flex1n",
    team: "Dragon Ranger Gaming",
    role: "Smokes",
    acs: 200,
    kd: 1.04,
    cl: "N/A",
    adr: 124,
    fk: 7,
  },
  {
    ign: "Akeman",
    team: "Dragon Ranger Gaming",
    role: "Duelist",
    acs: 197,
    kd: 0.86,
    cl: "N/A",
    adr: 129,
    fk: 10,
  },
  {
    ign: "Nicc",
    team: "Dragon Ranger Gaming",
    role: "Flex",
    acs: 189,
    kd: 0.92,
    cl: "N/A",
    adr: 126,
    fk: 5,
  },

  {
    ign: "free1ng",
    team: "DRX",
    role: "Flex",
    acs: 199,
    kd: 1.07,
    cl: "15.97%",
    adr: 131,
    fk: 11,
  },
  {
    ign: "MaKo",
    team: "DRX",
    role: "Smokes",
    acs: 202,
    kd: 1.06,
    cl: "14.79%",
    adr: 131,
    fk: 9,
  },
  {
    ign: "Estrella",
    team: "DRX",
    role: "Dart",
    acs: 158,
    kd: 0.79,
    cl: "14.29%",
    adr: 101,
    fk: 5,
  },
  {
    ign: "flashback",
    team: "DRX",
    role: "Sentinel",
    acs: 197,
    kd: 1.08,
    cl: "13.82%",
    adr: 132,
    fk: 10,
  },
  {
    ign: "HYUNMIN",
    team: "DRX",
    role: "Duelist",
    acs: 239,
    kd: 1.14,
    cl: "10.71%",
    adr: 154,
    fk: 19,
  },

  {
    ign: "Jieni7",
    team: "Edward Gaming",
    role: "Duelist",
    acs: 196,
    kd: 0.94,
    cl: "N/A",
    adr: 125,
    fk: 11,
  },
  {
    ign: "CHICHOO",
    team: "Edward Gaming",
    role: "Sentinel",
    acs: 206,
    kd: 1.11,
    cl: "22.00%",
    adr: 139,
    fk: 7,
  },
  {
    ign: "Smoggy",
    team: "Edward Gaming",
    role: "Smokes",
    acs: 199,
    kd: 1.06,
    cl: "20.00%",
    adr: 127,
    fk: 7,
  },
  {
    ign: "ZmjjKK",
    team: "Edward Gaming",
    role: "Duelist",
    acs: 250,
    kd: 1.15,
    cl: "4.00%",
    adr: 154,
    fk: 19,
  },
  {
    ign: "nobody",
    team: "Edward Gaming",
    role: "Dart",
    acs: 194,
    kd: 1.01,
    cl: "4.00%",
    adr: 128,
    fk: 10,
  },

  {
    ign: "kaajak",
    team: "FNATIC",
    role: "Duelist",
    acs: 235,
    kd: 1.23,
    cl: "20.37%",
    adr: 152,
    fk: 18,
  },
  {
    ign: "Boaster",
    team: "FNATIC",
    role: "Smokes",
    acs: 152,
    kd: 0.83,
    cl: "20.14%",
    adr: 100,
    fk: 7,
  },
  {
    ign: "crashies",
    team: "FNATIC",
    role: "Flex",
    acs: 183,
    kd: 1.06,
    cl: "16.43%",
    adr: 129,
    fk: 5,
  },
  {
    ign: "Alfajer",
    team: "FNATIC",
    role: "Sentinel",
    acs: 232,
    kd: 1.17,
    cl: "14.58%",
    adr: 152,
    fk: 15,
  },
  {
    ign: "Chronicle",
    team: "FNATIC",
    role: "Dart",
    acs: 205,
    kd: 1.1,
    cl: "9.69%",
    adr: 136,
    fk: 9,
  },

  {
    ign: "trent",
    team: "G2 Esports",
    role: "Dart",
    acs: 210,
    kd: 1.24,
    cl: "23.36%",
    adr: 141,
    fk: 8,
  },
  {
    ign: "jawgemo",
    team: "G2 Esports",
    role: "Duelist",
    acs: 218,
    kd: 1.06,
    cl: "17.65%",
    adr: 140,
    fk: 17,
  },
  {
    ign: "valyn",
    team: "G2 Esports",
    role: "Smokes",
    acs: 197,
    kd: 1.08,
    cl: "17.24%",
    adr: 126,
    fk: 8,
  },
  {
    ign: "leaf",
    team: "G2 Esports",
    role: "Sentinel",
    acs: 223,
    kd: 1.16,
    cl: "17.09%",
    adr: 147,
    fk: 13,
  },
  {
    ign: "JonahP",
    team: "G2 Esports",
    role: "Flex",
    acs: 181,
    kd: 0.95,
    cl: "15.07%",
    adr: 114,
    fk: 8,
  },

  {
    ign: "grubinho",
    team: "GIANTX",
    role: "Smokes",
    acs: 203,
    kd: 1.01,
    cl: "23.68%",
    adr: 132,
    fk: 10,
  },
  {
    ign: "Flickless",
    team: "GIANTX",
    role: "Flex",
    acs: 190,
    kd: 0.93,
    cl: "14.71%",
    adr: 123,
    fk: 7,
  },
  {
    ign: "ara",
    team: "GIANTX",
    role: "Duelist",
    acs: 218,
    kd: 1.11,
    cl: "14.67%",
    adr: 141,
    fk: 18,
  },
  {
    ign: "westside",
    team: "GIANTX",
    role: "Sentinel",
    acs: 190,
    kd: 1,
    cl: "13.61%",
    adr: 125,
    fk: 9,
  },
  {
    ign: "Cloud",
    team: "GIANTX",
    role: "Dart",
    acs: 194,
    kd: 0.96,
    cl: "7.09%",
    adr: 129,
    fk: 9,
  },

  {
    ign: "Verno",
    team: "MIBR",
    role: "Dart",
    acs: 188,
    kd: 1.03,
    cl: "18.90%",
    adr: 127,
    fk: 6,
  },
  {
    ign: "aspas",
    team: "MIBR",
    role: "Duelist",
    acs: 233,
    kd: 1.26,
    cl: "17.70%",
    adr: 150,
    fk: 19,
  },
  {
    ign: "xenom",
    team: "MIBR",
    role: "Smokes",
    acs: 177,
    kd: 0.98,
    cl: "15.66%",
    adr: 116,
    fk: 6,
  },
  {
    ign: "artzin",
    team: "MIBR",
    role: "Flex",
    acs: 182,
    kd: 0.79,
    cl: "13.75%",
    adr: 118,
    fk: 11,
  },
  {
    ign: "cortezia",
    team: "MIBR",
    role: "sentinel",
    acs: 197,
    kd: 1,
    cl: "13.28%",
    adr: 130,
    fk: 9,
  },

  {
    ign: "s0m",
    team: "NRG",
    role: "Sentinel",
    acs: 202,
    kd: 1.05,
    cl: "17.48%",
    adr: 130,
    fk: 9,
  },
  {
    ign: "Ethan",
    team: "NRG",
    role: "flex",
    acs: 196,
    kd: 0.98,
    cl: "16.28%",
    adr: 126,
    fk: 7,
  },
  {
    ign: "mada",
    team: "NRG",
    role: "Duelist",
    acs: 240,
    kd: 1.17,
    cl: "15.52%",
    adr: 156,
    fk: 23,
  },
  {
    ign: "skuba",
    team: "NRG",
    role: "smokes",
    acs: 191,
    kd: 1.14,
    cl: "14.13%",
    adr: 128,
    fk: 6,
  },
  {
    ign: "brawk",
    team: "NRG",
    role: "Dart",
    acs: 201,
    kd: 1.1,
    cl: "8.62%",
    adr: 135,
    fk: 6,
  },

  {
    ign: "f0rsakeN",
    team: "Paper Rex",
    role: "Flex",
    acs: 217,
    kd: 1.12,
    cl: "27.08%",
    adr: 141,
    fk: 12,
  },
  {
    ign: "patmen",
    team: "Paper Rex",
    role: "Smokes",
    acs: 183,
    kd: 0.98,
    cl: "18.97%",
    adr: 120,
    fk: 5,
  },
  {
    ign: "something",
    team: "Paper Rex",
    role: "Duelist",
    acs: 207,
    kd: 1.11,
    cl: "14.61%",
    adr: 132,
    fk: 15,
  },
  {
    ign: "Jinggg",
    team: "Paper Rex",
    role: "Duelist",
    acs: 226,
    kd: 1.16,
    cl: "12.40%",
    adr: 149,
    fk: 12,
  },
  {
    ign: "d4v41",
    team: "Paper Rex",
    role: "Flex",
    acs: 196,
    kd: 1.1,
    cl: "11.90%",
    adr: 133,
    fk: 8,
  },

  {
    ign: "Monyet",
    team: "Rex Regum Qeon",
    role: "Smokes",
    acs: 200,
    kd: 1,
    cl: "20.30%",
    adr: 129,
    fk: 10,
  },
  {
    ign: "xffero",
    team: "Rex Regum Qeon",
    role: "Sentinel",
    acs: 186,
    kd: 1.05,
    cl: "17.75%",
    adr: 124,
    fk: 7,
  },
  {
    ign: "Kushy",
    team: "Rex Regum Qeon",
    role: "Dart",
    acs: 185,
    kd: 0.95,
    cl: "16.13%",
    adr: 123,
    fk: 6,
  },
  {
    ign: "crazyguy",
    team: "Rex Regum Qeon",
    role: "Flex",
    acs: 177,
    kd: 0.89,
    cl: "11.76%",
    adr: 116,
    fk: 7,
  },
  {
    ign: "Jemkin",
    team: "Rex Regum Qeon",
    role: "Duelist",
    acs: 241,
    kd: 1.25,
    cl: "11.45%",
    adr: 152,
    fk: 21,
  },

  {
    ign: "N4RRATE",
    team: "Sentinels",
    role: "Dart",
    acs: 210,
    kd: 1.05,
    cl: "20.44%",
    adr: 137,
    fk: 10,
  },
  {
    ign: "bang",
    team: "Sentinels",
    role: "Smokes",
    acs: 197,
    kd: 1.06,
    cl: "17.73%",
    adr: 123,
    fk: 9,
  },
  {
    ign: "zekken",
    team: "Sentinels",
    role: "Duelist",
    acs: 230,
    kd: 1.17,
    cl: "17.46%",
    adr: 146,
    fk: 21,
  },
  {
    ign: "zellsis",
    team: "Sentinels",
    role: "Sentinel",
    acs: 182,
    kd: 0.93,
    cl: "12.39%",
    adr: 120,
    fk: 8,
  },
  {
    ign: "johnqt",
    team: "Sentinels",
    role: "Flex",
    acs: 184,
    kd: 1.1,
    cl: "8.43%",
    adr: 123,
    fk: 6,
  },

  {
    ign: "DH",
    team: "T1",
    role: "Smokes",
    acs: 199,
    kd: 1.07,
    cl: "26.09%",
    adr: 127,
    fk: 8,
  },
  {
    ign: "iZu",
    team: "T1",
    role: "Duelist",
    acs: 199,
    kd: 1.06,
    cl: "18.66%",
    adr: 130,
    fk: 9,
  },
  {
    ign: "stax",
    team: "T1",
    role: "Dart",
    acs: 170,
    kd: 0.93,
    cl: "13.60%",
    adr: 116,
    fk: 4,
  },
  {
    ign: "BuZz",
    team: "T1",
    role: "Flex",
    acs: 225,
    kd: 1.07,
    cl: "12.90%",
    adr: 145,
    fk: 17,
  },
  {
    ign: "Meteor",
    team: "T1",
    role: "Sentinel",
    acs: 218,
    kd: 1.03,
    cl: "9.73%",
    adr: 143,
    fk: 13,
  },

  {
    ign: "Wo0t",
    team: "Team Heretics",
    role: "Flex",
    acs: 218,
    kd: 1.12,
    cl: "21.11%",
    adr: 141,
    fk: 13,
  },
  {
    ign: "MiniBoo",
    team: "Team Heretics",
    role: "Duelist",
    acs: 222,
    kd: 1.07,
    cl: "17.39%",
    adr: 142,
    fk: 19,
  },
  {
    ign: "RieNs",
    team: "Team Heretics",
    role: "Dart",
    acs: 213,
    kd: 1.09,
    cl: "15.91%",
    adr: 143,
    fk: 8,
  },
  {
    ign: "Benjyfishy",
    team: "Team Heretics",
    role: "Sentinel",
    acs: 190,
    kd: 1.02,
    cl: "14.39%",
    adr: 127,
    fk: 7,
  },
  {
    ign: "Boo",
    team: "Team Heretics",
    role: "Smokes",
    acs: 158,
    kd: 0.83,
    cl: "11.88%",
    adr: 101,
    fk: 7,
  },

  {
    ign: "trexx",
    team: "Team Liquid",
    role: "Dart",
    acs: 202,
    kd: 1.07,
    cl: "19.12%",
    adr: 130,
    fk: 7,
  },
  {
    ign: "kamo",
    team: "Team Liquid",
    role: "Duelist",
    acs: 212,
    kd: 1.02,
    cl: "17.27%",
    adr: 138,
    fk: 17,
  },
  {
    ign: "Keiko",
    team: "Team Liquid",
    role: "Flex",
    acs: 223,
    kd: 1.23,
    cl: "16.34%",
    adr: 146,
    fk: 11,
  },
  {
    ign: "paTiTek",
    team: "Team Liquid",
    role: "Flex",
    acs: 175,
    kd: 0.93,
    cl: "14.07%",
    adr: 115,
    fk: 8,
  },
  {
    ign: "nAts",
    team: "Team Liquid",
    role: "Sentinel",
    acs: 216,
    kd: 1.12,
    cl: "12.81%",
    adr: 142,
    fk: 11,
  },

  {
    ign: "NoMan",
    team: "Xi Lai Gaming",
    role: "Sentinel",
    acs: 190,
    kd: 1.03,
    cl: "N/A",
    adr: 130,
    fk: 13,
  },
  {
    ign: "Viva",
    team: "Xi Lai Gaming",
    role: "Dart",
    acs: 165,
    kd: 0.89,
    cl: "N/A",
    adr: 116,
    fk: 5,
  },
  {
    ign: "Rarga",
    team: "Xi Lai Gaming",
    role: "Flex",
    acs: 243,
    kd: 1.21,
    cl: "33.00%",
    adr: 165,
    fk: 20,
  },
  {
    ign: "coconut",
    team: "Xi Lai Gaming",
    role: "Smokes",
    acs: 174,
    kd: 0.94,
    cl: "23.00%",
    adr: 112,
    fk: 5,
  },
  {
    ign: "happywei",
    team: "Xi Lai Gaming",
    role: "Sentinel",
    acs: 235,
    kd: 1.17,
    cl: "12.00%",
    adr: 150,
    fk: 13,
  },
];
export const team_data: team[] = [
  {
    name: "Paper Rex",
    short_name: "prx",
    region: "APAC",
    players: ["d4v41", "f0rsaken", "jinggg", "patmen", "something"],
    timeOfMatch: new Date("2025-09-12T13:00:00Z"),
    opponent: "xlg",
    rank: "1",
    color: "#FF0066",
  },
  {
    name: "Sentinels",
    short_name: "sen",
    region: "NA",
    players: ["bang", "johnqt", "n4rrate", "zekken", "zellsis"],
    timeOfMatch: new Date("2025-09-12T16:00:00Z"),
    opponent: "gx",
    rank: "8",
    color: "#ce0037",
  },
  {
    name: "NRG",
    short_name: "nrg",
    region: "NA",
    players: ["brawk", "ethan", "mada", "s0m", "skuba"],
    timeOfMatch: new Date("2025-09-13T13:00:00Z"),
    opponent: "edg",
    rank: "7",
    color: "#F73D0A",
  },
  {
    name: "Team Liquid",
    short_name: "tl",
    region: "EMEA",
    players: ["kamo", "keiko", "nats", "patitek", "trexx"],
    timeOfMatch: new Date("2025-09-13T16:00:00Z"),
    opponent: "drx",
    rank: "3",
    color: "#EEEEEE",
  },
  {
    name: "DRG",
    short_name: "drg",
    region: "CHINA",
    players: ["akeman", "flex1n", "nicc", "spiritz1", "vo0kashu"],
    timeOfMatch: new Date("2025-09-14T13:00:00Z"),
    opponent: "t1",
    rank: "13",
    color: "#2E60F9",
  },
  {
    name: "G2 Esports",
    short_name: "g2",
    region: "NA",
    players: ["jawgemo", "jonahp", "leaf", "trent", "valyn"],
    timeOfMatch: new Date("2025-09-14T16:00:00Z"),
    opponent: "th",
    rank: "2",
    color: "#FFFFFF",
  },
  {
    name: "Bilibili Gaming",
    short_name: "blg",
    region: "CHINA",
    players: ["knight", "levius", "nephh", "rushia", "whzy"],
    timeOfMatch: new Date("2025-09-15T13:00:00Z"),
    opponent: "mibr",
    rank: "4",
    color: "#36D0F4",
  },
  {
    name: "Rex Regum Qeon",
    short_name: "rrq",
    region: "APAC",
    players: ["crazyguy", "jemkin", "kushy", "monyet", "xffero"],
    timeOfMatch: new Date("2025-09-16T16:00:00Z"),
    opponent: "fnc",
    rank: "6",
    color: "#F3AA36",
  },
  {
    name: "Xi Lai Gaming",
    short_name: "xlg",
    region: "CHINA",
    players: ["coconut", "happywei", "NoMan", "rarga", "Viva"],
    timeOfMatch: new Date("2025-09-12T13:00:00Z"),
    opponent: "prx",
    rank: "15",
    color: "#04559F",
  },
  {
    name: "GIANTX",
    short_name: "gx",
    region: "EMEA",
    players: ["ara", "cloud", "flickless", "grubinho", "westside"],
    timeOfMatch: new Date("2025-09-12T16:00:00Z"),
    opponent: "sen",
    rank: "11",
    color: "#FFFFFF",
  },
  {
    name: "Edward Gaming",
    short_name: "edg",
    region: "CHINA",
    players: ["chichoo", "jieni7", "nobody", "smoggy", "zmjjkk"],
    timeOfMatch: new Date("2025-09-13T13:00:00Z"),
    opponent: "nrg",
    rank: "12",
    color: "#FFFFFF",
  },
  {
    name: "DRX",
    short_name: "drx",
    region: "APAC",
    players: ["estrella", "flashback", "free1ng", "hyunmin", "MaKo"],
    timeOfMatch: new Date("2025-09-13T16:00:00Z"),
    opponent: "tl",
    rank: "14",
    color: "#0F03A3",
  },
  {
    name: "T1",
    short_name: "t1",
    region: "APAC",
    players: ["BuZz", "DH", "iZu", "meteor", "stax"],
    timeOfMatch: new Date("2025-09-14T13:00:00Z"),
    opponent: "drg",
    rank: "10",
    color: "#E2012D",
  },
  {
    name: "Team Heretics",
    short_name: "th",
    region: "EMEA",
    players: ["Boo", "Miniboo", "Wo0t", "RieNs", "benjyfishy"],
    timeOfMatch: new Date("2025-09-14T16:00:00Z"),
    opponent: "g2",
    rank: "9",
    color: "#DBA611",
  },
  {
    name: "MIBR",
    short_name: "mibr",
    region: "SA",
    players: ["Artzin", "aspas", "cortezia", "verno", "xenom"],
    timeOfMatch: new Date("2025-09-15T13:00:00Z"),
    opponent: "blg",
    rank: "16",
    color: "#FFFFFF",
  },
  {
    name: "FNATIC",
    short_name: "fnc",
    region: "Emea",
    players: ["alfajer", "boaster", "chronicle", "crashies", "kaajak"],
    timeOfMatch: new Date("2025-09-16T16:00:00Z"),
    opponent: "rrq",
    rank: "6",
    color: "#FF5900",
  },
];
